// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InformationalPrompt } from "./InformationalPrompt";
import type { QuestionFields } from "./QuestionFields";
import type { ShortAnswerAnswer } from "./ShortAnswerAnswer";

export type Informational = QuestionFields<InformationalPrompt, ShortAnswerAnswer>;