// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MultipleChoiceAnswer } from "./MultipleChoiceAnswer";
import type { MultipleChoicePrompt } from "./MultipleChoicePrompt";
import type { QuestionFields } from "./QuestionFields";

export type MultipleChoice = QuestionFields<MultipleChoicePrompt, MultipleChoiceAnswer>;