// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Markdown } from "./Markdown";

export interface MultipleChoicePrompt { prompt: Markdown, distractors: Array<Markdown>, answerIndex?: number, sortAnswers?: boolean, }