// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MultipleChoice } from "./MultipleChoice";
import type { ShortAnswer } from "./ShortAnswer";
import type { Tracing } from "./Tracing";
import type { Informational } from "./Informational";

export type Question = { "type": "ShortAnswer" } & ShortAnswer | { "type": "Tracing" } & Tracing | { "type": "MultipleChoice" } & MultipleChoice | { "type": "Informational" } & Informational;