// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Markdown } from "./Markdown";

export interface QuestionFields<Prompt, Answer> { id?: string, multipart?: string, prompt: Prompt, answer: Answer, context?: Markdown, promptExplanation?: boolean, }