// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Markdown } from "./Markdown";
import type { Question } from "./Question";

export interface Quiz { questions: Array<Question>, multipart?: Record<string, Markdown>, }