// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuestionFields } from "./QuestionFields";
import type { ShortAnswerAnswer } from "./ShortAnswerAnswer";
import type { ShortAnswerPrompt } from "./ShortAnswerPrompt";

export type ShortAnswer = QuestionFields<ShortAnswerPrompt, ShortAnswerAnswer>;