// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Markdown } from "./Markdown";
import type { ShortAnswerResponseFormat } from "./ShortAnswerResponseFormat";

export interface ShortAnswerPrompt { prompt: Markdown, response?: ShortAnswerResponseFormat, }