// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuestionFields } from "./QuestionFields";
import type { TracingAnswer } from "./TracingAnswer";
import type { TracingPrompt } from "./TracingPrompt";

export type Tracing = QuestionFields<TracingPrompt, TracingAnswer>;